name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update PDF
          file_pattern: 'main.pdf'
